### PR TITLE
[WIP] Desktop view update, UI fixes, Code restructuring, and File management.

### PR DESCRIPTION
**Pull request by osaroadade**
Hey, I came across this repo through a friend and I felt it could be better so I decided to redesign it. I worked on the general UI, the desktop view, code restructuring and file management. I am still working on the responsiveness on smaller screens.
This was fun to work on and I must commend your skills. Thanks for sharing. ✌✌

### CODE REVIEW

**Comment by Anita-Jamgbadi** [comment]
Hey there,

You must be Daniel's friend right? I saw your work, and I must say although
it was a lot different from what I originally designed its a very
innovative and clean design with no perceptible rough edges.
Great work.
Also, thank you for reaching out. I appreciate your courtesy.
Have a great day,

-Anita.

**Comment by osaroadade** [comment]
Not Daniel's, David. Thank you very much.
You are also welcome. 👌👌

**Comment by Anita-Jamgbadi** [comment]
Yeah, I realized after I sent the email.
Youre welcome.

**Comment by osaroadade** [comment]
Let me know whenever you're in need of collaboration, I'd love to work with you sometime. 💼

**Comment by Anita-Jamgbadi** [comment]
I sure will, you can contact me too if you want to collaborate.

**Comment by osaroadade** [comment]
Sure thing. ✌✌
Is there a live version of the ace-playhouse running beside the GitHub page you created?

**Pull request closed without merging**
